config/routes.rb
Rails.application.routes.draw do
  resources :sub_acts
  resources :main_acts
  resources :users
  resources :completions do
    post :undo, on: :member
    collection do
      post :create_with_count
    end
  end

  get "/login", to: "application#login"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :sub_act
end

app/models/main_act.rb
class MainAct < ApplicationRecord
  belongs_to :user
  has_many :sub_acts
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user, required: true
end

app/models/sub_act.rb
class SubAct < ApplicationRecord
  belongs_to :main_act
  has_many :completions
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :main_acts
  has_many :sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user, except: [:login, :index]

  def login
    password = params[:password]
    if password == Rails.application.credentials.dig(:password)
      cookies.signed[:session_id] = Rails.application.credentials.dig(:token)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def authenticate_user
    if authorization_token != Rails.application.credentials.dig(:token)
      redirect_to root_path
    end
  end

  def authorization_token
    cookies.signed[:session_id]
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def undo
    completion = Completion.find(params[:id]).destroy

    redirect_to "#{url_for(root_path)}#main-#{completion.sub_act.main_act.id}"
  end

  def create
    completion = Completion.create!(sub_act_id: params[:sub_act_id])
    redirect_to "#{url_for(root_path)}#main-#{completion.sub_act.main_act.id}"
  end

  def create_with_count
    Completion.create!(sub_act_id: params[:sub_act_id])
    sub_act = SubAct.find(params[:sub_act_id])

    metadata = sub_act.metadata
    metadata["have"] = params[:have].to_i
    metadata["need"] = params[:need].to_i
    metadata["get"] = params[:get].to_i

    sub_act.update!(metadata: metadata)

    redirect_to "#{url_for(root_path)}#main-#{sub_act.main_act.id}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_acts = MainAct.order(:name)
    @completions = {}
    @sub_acts_count = @main_acts.map(&:sub_acts).flatten.count

    @main_acts.map(&:sub_acts).flatten.each do |sub_act|
      if sub_act.metadata["reset"] == "weekly"
        completion = Completion.where(sub_act: sub_act).where("created_at > ?", DateTime.now.beginning_of_week(:wednesday).change({hour: 7, minute: 0})).first
        if completion.present?
          @completions[sub_act.id] = completion
        end
      elsif sub_act.metadata["reset"] == "half"
        wed_reset = DateTime.now.beginning_of_week(:wednesday).change({hour: 7, minute: 0})
        sat_reset = DateTime.now.beginning_of_week(:saturday).change({hour: 19, minute: 0})

        relevant_date = sat_reset < wed_reset ? wed_reset : sat_reset

        completion = Completion.where(sub_act: sub_act).where("created_at > ?", relevant_date).first
        if completion.present? 
          @completions[sub_act.id] = completion
        end
      elsif sub_act.metadata["reset"] == "daily"
        completion = Completion.where(sub_act: sub_act).where("created_at > ?", Date.yesterday.change({hour: 7, minute: 0})).first
        if Time.now.hour < 7 && completion.present?
          @completions[sub_act.id] = completion
        end
        completion = Completion.where(sub_act: sub_act).where("created_at > ?", Time.now.change({hour: 7, minute: 0})).first
        if Time.now.hour >= 7 && completion.present?
          @completions[sub_act.id] = completion
        end
      end
    end

    @meta_completion = 0
    @main_acts.map do |main_act|
      if (main_act.sub_acts.pluck(:id) - @completions.keys).empty?
        @meta_completion += 1
      end
    end

  end
end

app/controllers/main_acts_controller.rb
class MainActsController < ApplicationController
  def create
    permitted_params = params.permit(:user_id, :name)
    MainAct.create!(permitted_params)

    redirect_back fallback_location: root_path
  end

  def destroy
    MainAct.find(params[:id]).destroy

    redirect_back fallback_location: root_path
  end
end

app/controllers/sub_acts_controller.rb
class SubActsController < ApplicationController
  def create
    permitted_params = params.permit(:name, :main_act_id, metadata: {})
    metadata = permitted_params.delete :metadata

    metadata["have"] = metadata["have"].to_i
    metadata["need"] = metadata["need"].to_i
    metadata["get"] = metadata["get"].to_i
    sub_act = SubAct.new(permitted_params)
    sub_act.metadata = metadata

    sub_act.save!

    redirect_back fallback_location: root_path
  end

  def destroy
    SubAct.find(params[:id]).destroy
  
    redirect_back fallback_location: root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def kind_span_tag(sub_act)
    case sub_act.metadata["kind"]
    when "rare_kill"
      content_tag(:span, "Rare", class: ["span-tag", "rare-kill"])
    when "count"
      content_tag(:span, "Collect", class: ["span-tag", "collect"])
    when "action"
      content_tag(:span, "Action", class: ["span-tag", "action"])
    when "quest_check"
      content_tag(:span, "Quest", class: ["span-tag", "quest"])
    when "raid_boss"
      content_tag(:span, "Raid", class: ["span-tag", "raid-boss"])
    end  
  end

  def reset_span_tag(sub_act)
    case sub_act.metadata["reset"]
    when "daily"
      content_tag(:span, "D", class: ["span-tag", "daily"])
    when "weekly"
      content_tag(:span, "W", class: ["span-tag", "weekly"])
    when "half"
      content_tag(:span, "H", class: ["span-tag", "half-week"])
    end  
  end

  def hint_tag(sub_act)
    metadata = sub_act.metadata
    case metadata["kind"]
    when "rare_kill"
      content_tag(:p, metadata["hint"] || "Kill the rare", class: ["describe-action"])
    when "raid_boss"
      content_tag(:p, metadata["hint"] || "Kill the raid boss", class: ["describe-action"])
    when "count"
      have = metadata["have"] || 1
      need = metadata["need"] || 1
      get = metadata["get"] || 1
      [
        content_tag(:p, "#{have} / #{need}", class: ["count-action"]),
        content_tag(:p, "Get #{get}", class: ["count-action"]),
        content_tag(:p, "Times left: #{((need - have) / get.to_f)}", class: ["count-action"])
      ].join.html_safe
    when "action"
      content_tag(:p, metadata["hint"] || "Do something", class: ["describe-action"])
    when "quest_check"
      content_tag(:p, metadata["hint"] || "Check for quest", class: ["describe-action"])
    end  
  end

  def completion_button(sub_act)
    metadata = sub_act.metadata
    case metadata["kind"]
    when "rare_kill"
      render "completion/simple", sub_act: sub_act
    when "count"
      render "completion/count", sub_act: sub_act
    when "action"
      render "completion/simple", sub_act: sub_act
    when "quest_check"
      render "completion/simple", sub_act: sub_act
    when "raid_boss"
      render "completion/simple", sub_act: sub_act
    end
  end

  def done_button(sub_act)
    metadata = sub_act.metadata
    case metadata["kind"]
    when "rare_kill"
      button_to "Done", do_completions_path, class: "button"
    when "count"
      button_to "Done", do_completions_path, class: "button"
    when "action"
      button_to "Done", do_completions_path, class: "button"
    when "quest_check"
      button_to "Done", do_completions_path, class: "button"
    when "raid_boss"
      button_to "Done", do_completions_path, class: "button"
    end
  end
end

app/helpers/main_acts_helper.rb
module MainActsHelper
end

app/helpers/sub_acts_helper.rb
module SubActsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/completion/_count.html.slim
.modal id="count-modal-js-#{sub_act.id}"
  .modal-background
  .modal-card
    .modal-card-head.has-background-info
      p.modal-card-title.has-text-white
        | Collection done
    .modal-card-body
      = form_with url: create_with_count_completions_path do |form|
        = form.hidden_field :sub_act_id, value: sub_act.id
        .field
          = form.label "Have"
          = form.number_field :have, value: sub_act.metadata["have"], class: "input"

        .field
          = form.label "Need"
          = form.number_field :need, value: sub_act.metadata["need"], class: "input"

        .field
          = form.label "Get"
          = form.number_field :get, value: sub_act.metadata["get"], class: "input"


        = form.submit "Done", class: "button"
  button.modal-close.is-large aria-label="close" 

button.js-modal-trigger.button data-target="count-modal-js-#{sub_act.id}" 
  | Done

app/views/completion/_simple.html.slim
= form_with url: completions_path do |form|
  = form.hidden_field :sub_act_id, value: sub_act.id

  = form.submit "Done", class: "button"

app/views/home/index.html.slim
= render "main_acts/new"
= render "sub_acts/new"

.is-flex.is-justify-content-space-between.is-align-items-center
  p.is-size-3
    = "Meta Objectives: #{@meta_completion} / #{@main_acts.count}"
  .sub-act-actions
    button.button.js-modal-trigger data-target="new-meta"
      = "New Meta"
    button.button.js-modal-trigger data-target="new-sub"
      = "New Sub"
  p.is-size-3
    = "Sub Objectives: #{@completions.count} / #{@sub_acts_count}"

- @main_acts.each do |main_act|
  div id="main-#{main_act.id}"
  .mb-4.is-flex.is-justify-content-space-between.is-align-items-center.is-title
    p.is-size-3.bordered-title 
      = main_act.name
    .sub-act-actions
      = button_to "Remove", main_act_path(main_act.id), method: :delete, class: "button is-inverted is-danger", onclick: "return confirm('Are you sure ?')"
      - if (main_act.sub_acts.pluck(:id) - @completions.keys).empty?
        .button.is-info.is-inverted.sub-js-trigger data-target="sub-js-#{main_act.id}"
          = "Show"
      - else
        .button.is-info.is-inverted.sub-js-trigger data-target="sub-js-#{main_act.id}"
          = "Hide"
      - if (main_act.sub_acts.pluck(:id) - @completions.keys).empty?
        | ✅
      - else
        | ❌


  div id="sub-js-#{main_act.id}" class=((main_act.sub_acts.pluck(:id) - @completions.keys).empty? ? "d-none" : "")
    - main_act.sub_acts.order(:name).each do |sub_act|
      .is-flex.is-align-items-center.is-justify-content-space-between.py-2
        .sub-act-title
          .is-flex.is-justify-content-end.is-align-items-center
            p.is-size-5 = sub_act.name
            = kind_span_tag(sub_act)
            = reset_span_tag(sub_act)
        = hint_tag(sub_act)
        .sub-act-actions
          = button_to "🗑", sub_act_path(sub_act.id), method: :delete, class: "button is-inverted is-danger", onclick: "return confirm('Are you sure ?')"
          - if @completions.include?(sub_act.id)
            = button_to "Undo", undo_completion_path(@completions[sub_act.id].id), class: "button"
            | ✅
          - else
            = completion_button(sub_act)
            | ❌
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WowTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body> 
    <div class="container container-main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main_acts/_new.html.slim
#new-meta.modal
  .modal-background
  .modal-card
    .modal-card-head.has-background-info
      p.modal-card-title.has-text-white
        | New Meta Group
    .modal-card-body
      = form_with url: main_acts_path do |form|
        = form.hidden_field :user_id, value: User.first.id
        .field
          = form.label "Name"
          = form.text_field :name, class: "input"

        = form.submit "Create", class: "button"
  button.modal-close.is-large aria-label="close" 

app/views/shared/_header.html.slim
.is-flex.is-justify-content-center.is-align-items-center.has-background-info.has-text-white
  h2.is-size-2 = "Hi Stormy"

  

app/views/sub_acts/_new.html.slim
#new-sub.modal
  .modal-background
  .modal-card
    .modal-card-head.has-background-info
      p.modal-card-title.has-text-white
        | New Sub Act
    .modal-card-body
      = form_with url: sub_acts_path do |form|
        = form.hidden_field :user, value: User.first.id
        .field
          = form.label "Name"
          = form.text_field :name, class: "input"

        .meta-field
          = form.label "Meta Group"
          .select
            = form.select :main_act_id, options_for_select(MainAct.all.order(:name).pluck(:name, :id))

        .meta-field
          = form.label "Kind"
          .select
            = form.select "metadata[kind]", options_for_select([["Collect", "count"], ["Quest Check", "quest_check"], ["Rare Kill", "rare_kill"], ["Raid Boss", "raid_boss"], ["Action", "action"]])

        .meta-field
          = form.label "Reset"
          .select
            = form.select "metadata[reset]", options_for_select([["Daily", "daily"], ["Weekly", "weekly"], ["Half Week", "half"]])

        .meta-field
          = form.label "Hint"
          = form.text_field "metadata[hint]", class: "input half-width"

        .meta-field
          = form.label "Have"
          = form.number_field "metadata[have]", class: "input half-width"

        .meta-field
          = form.label "Need"
          = form.number_field "metadata[need]", class: "input half-width"

        .meta-field
          = form.label "Get"
          = form.number_field "metadata[get]", class: "input half-width"

        = form.submit "Create", class: "button"
  button.modal-close.is-large aria-label="close" 